// Code generated by mockery v2.53.5. DO NOT EDIT.

package repository_mock

import (
	"time"

	models "sun-stockanalysis-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockRefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type MockRefreshTokenRepository struct {
	mock.Mock
}

type MockRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepository_Expecter {
	return &MockRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: token
func (_m *MockRefreshTokenRepository) Create(token *models.RefreshTokens) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.RefreshTokens) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - token *models.RefreshTokens
func (_e *MockRefreshTokenRepository_Expecter) Create(token interface{}) *MockRefreshTokenRepository_Create_Call {
	return &MockRefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", token)}
}

func (_c *MockRefreshTokenRepository_Create_Call) Run(run func(token *models.RefreshTokens)) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.RefreshTokens))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) Return(_a0 error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) RunAndReturn(run func(*models.RefreshTokens) error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByHash provides a mock function with given fields: hash
func (_m *MockRefreshTokenRepository) FindByHash(hash string) (*models.RefreshTokens, error) {
	ret := _m.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for FindByHash")
	}

	var r0 *models.RefreshTokens
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.RefreshTokens, error)); ok {
		return rf(hash)
	}
	if rf, ok := ret.Get(0).(func(string) *models.RefreshTokens); ok {
		r0 = rf(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RefreshTokens)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_FindByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByHash'
type MockRefreshTokenRepository_FindByHash_Call struct {
	*mock.Call
}

// FindByHash is a helper method to define mock.On call
//   - hash string
func (_e *MockRefreshTokenRepository_Expecter) FindByHash(hash interface{}) *MockRefreshTokenRepository_FindByHash_Call {
	return &MockRefreshTokenRepository_FindByHash_Call{Call: _e.mock.On("FindByHash", hash)}
}

func (_c *MockRefreshTokenRepository_FindByHash_Call) Run(run func(hash string)) *MockRefreshTokenRepository_FindByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_FindByHash_Call) Return(_a0 *models.RefreshTokens, _a1 error) *MockRefreshTokenRepository_FindByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_FindByHash_Call) RunAndReturn(run func(string) (*models.RefreshTokens, error)) *MockRefreshTokenRepository_FindByHash_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBefore provides a mock function with given fields: t
func (_m *MockRefreshTokenRepository) DeleteBefore(t time.Time) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBefore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeByHash provides a mock function with given fields: hash, revokedAt
func (_m *MockRefreshTokenRepository) RevokeByHash(hash string, revokedAt float64) error {
	ret := _m.Called(hash, revokedAt)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64) error); ok {
		r0 = rf(hash, revokedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_RevokeByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByHash'
type MockRefreshTokenRepository_RevokeByHash_Call struct {
	*mock.Call
}

// RevokeByHash is a helper method to define mock.On call
//   - hash string
//   - revokedAt float64
func (_e *MockRefreshTokenRepository_Expecter) RevokeByHash(hash interface{}, revokedAt interface{}) *MockRefreshTokenRepository_RevokeByHash_Call {
	return &MockRefreshTokenRepository_RevokeByHash_Call{Call: _e.mock.On("RevokeByHash", hash, revokedAt)}
}

func (_c *MockRefreshTokenRepository_RevokeByHash_Call) Run(run func(hash string, revokedAt float64)) *MockRefreshTokenRepository_RevokeByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(float64))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeByHash_Call) Return(_a0 error) *MockRefreshTokenRepository_RevokeByHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeByHash_Call) RunAndReturn(run func(string, float64) error) *MockRefreshTokenRepository_RevokeByHash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenRepository creates a new instance of MockRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
