// Code generated by mockery v2.53.5. DO NOT EDIT.

package repository_mock

import (
	models "sun-stockanalysis-api/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockStockRepository is an autogenerated mock type for the StockRepository type
type MockStockRepository struct {
	mock.Mock
}

type MockStockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStockRepository) EXPECT() *MockStockRepository_Expecter {
	return &MockStockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: stock
func (_m *MockStockRepository) Create(stock *models.Stock) error {
	ret := _m.Called(stock)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Stock) error); ok {
		r0 = rf(stock)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - stock *models.Stock
func (_e *MockStockRepository_Expecter) Create(stock interface{}) *MockStockRepository_Create_Call {
	return &MockStockRepository_Create_Call{Call: _e.mock.On("Create", stock)}
}

func (_c *MockStockRepository_Create_Call) Run(run func(stock *models.Stock)) *MockStockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Stock))
	})
	return _c
}

func (_c *MockStockRepository_Create_Call) Return(_a0 error) *MockStockRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStockRepository_Create_Call) RunAndReturn(run func(*models.Stock) error) *MockStockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureMasterAssetType provides a mock function with given fields: name
func (_m *MockStockRepository) EnsureMasterAssetType(name string) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for EnsureMasterAssetType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStockRepository_EnsureMasterAssetType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureMasterAssetType'
type MockStockRepository_EnsureMasterAssetType_Call struct {
	*mock.Call
}

// EnsureMasterAssetType is a helper method to define mock.On call
//   - name string
func (_e *MockStockRepository_Expecter) EnsureMasterAssetType(name interface{}) *MockStockRepository_EnsureMasterAssetType_Call {
	return &MockStockRepository_EnsureMasterAssetType_Call{Call: _e.mock.On("EnsureMasterAssetType", name)}
}

func (_c *MockStockRepository_EnsureMasterAssetType_Call) Run(run func(name string)) *MockStockRepository_EnsureMasterAssetType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStockRepository_EnsureMasterAssetType_Call) Return(_a0 error) *MockStockRepository_EnsureMasterAssetType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStockRepository_EnsureMasterAssetType_Call) RunAndReturn(run func(string) error) *MockStockRepository_EnsureMasterAssetType_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureMasterExchange provides a mock function with given fields: name
func (_m *MockStockRepository) EnsureMasterExchange(name string) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for EnsureMasterExchange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStockRepository_EnsureMasterExchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureMasterExchange'
type MockStockRepository_EnsureMasterExchange_Call struct {
	*mock.Call
}

// EnsureMasterExchange is a helper method to define mock.On call
//   - name string
func (_e *MockStockRepository_Expecter) EnsureMasterExchange(name interface{}) *MockStockRepository_EnsureMasterExchange_Call {
	return &MockStockRepository_EnsureMasterExchange_Call{Call: _e.mock.On("EnsureMasterExchange", name)}
}

func (_c *MockStockRepository_EnsureMasterExchange_Call) Run(run func(name string)) *MockStockRepository_EnsureMasterExchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStockRepository_EnsureMasterExchange_Call) Return(_a0 error) *MockStockRepository_EnsureMasterExchange_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStockRepository_EnsureMasterExchange_Call) RunAndReturn(run func(string) error) *MockStockRepository_EnsureMasterExchange_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureMasterSector provides a mock function with given fields: name
func (_m *MockStockRepository) EnsureMasterSector(name string) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for EnsureMasterSector")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStockRepository_EnsureMasterSector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureMasterSector'
type MockStockRepository_EnsureMasterSector_Call struct {
	*mock.Call
}

// EnsureMasterSector is a helper method to define mock.On call
//   - name string
func (_e *MockStockRepository_Expecter) EnsureMasterSector(name interface{}) *MockStockRepository_EnsureMasterSector_Call {
	return &MockStockRepository_EnsureMasterSector_Call{Call: _e.mock.On("EnsureMasterSector", name)}
}

func (_c *MockStockRepository_EnsureMasterSector_Call) Run(run func(name string)) *MockStockRepository_EnsureMasterSector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStockRepository_EnsureMasterSector_Call) Return(_a0 error) *MockStockRepository_EnsureMasterSector_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStockRepository_EnsureMasterSector_Call) RunAndReturn(run func(string) error) *MockStockRepository_EnsureMasterSector_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockStockRepository) FindByID(id uuid.UUID) (*models.Stock, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Stock
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Stock, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Stock); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Stock)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockStockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockStockRepository_Expecter) FindByID(id interface{}) *MockStockRepository_FindByID_Call {
	return &MockStockRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockStockRepository_FindByID_Call) Run(run func(id uuid.UUID)) *MockStockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockStockRepository_FindByID_Call) Return(_a0 *models.Stock, _a1 error) *MockStockRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStockRepository_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*models.Stock, error)) *MockStockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStockRepository creates a new instance of MockStockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStockRepository {
	mock := &MockStockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
