// Code generated by mockery v2.53.5. DO NOT EDIT.

package auth_mock

import (
	auth "sun-stockanalysis-api/internal/domains/auth"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: input
func (_m *MockAuthService) Login(input auth.LoginInput) (*auth.LoginResult, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *auth.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(auth.LoginInput) (*auth.LoginResult, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(auth.LoginInput) *auth.LoginResult); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.LoginResult)
		}
	}

	if rf, ok := ret.Get(1).(func(auth.LoginInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - input auth.LoginInput
func (_e *MockAuthService_Expecter) Login(input interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", input)}
}

func (_c *MockAuthService_Login_Call) Run(run func(input auth.LoginInput)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(auth.LoginInput))
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(_a0 *auth.LoginResult, _a1 error) *MockAuthService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(auth.LoginInput) (*auth.LoginResult, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: input
func (_m *MockAuthService) Refresh(input auth.RefreshInput) (*auth.LoginResult, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *auth.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(auth.RefreshInput) (*auth.LoginResult, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(auth.RefreshInput) *auth.LoginResult); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.LoginResult)
		}
	}

	if rf, ok := ret.Get(1).(func(auth.RefreshInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockAuthService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - input auth.RefreshInput
func (_e *MockAuthService_Expecter) Refresh(input interface{}) *MockAuthService_Refresh_Call {
	return &MockAuthService_Refresh_Call{Call: _e.mock.On("Refresh", input)}
}

func (_c *MockAuthService_Refresh_Call) Run(run func(input auth.RefreshInput)) *MockAuthService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(auth.RefreshInput))
	})
	return _c
}

func (_c *MockAuthService_Refresh_Call) Return(_a0 *auth.LoginResult, _a1 error) *MockAuthService_Refresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Refresh_Call) RunAndReturn(run func(auth.RefreshInput) (*auth.LoginResult, error)) *MockAuthService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: input
func (_m *MockAuthService) Register(input auth.RegisterInput) (*auth.RegisterResult, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *auth.RegisterResult
	var r1 error
	if rf, ok := ret.Get(0).(func(auth.RegisterInput) (*auth.RegisterResult, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(auth.RegisterInput) *auth.RegisterResult); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RegisterResult)
		}
	}

	if rf, ok := ret.Get(1).(func(auth.RegisterInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - input auth.RegisterInput
func (_e *MockAuthService_Expecter) Register(input interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", input)}
}

func (_c *MockAuthService_Register_Call) Run(run func(input auth.RegisterInput)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(auth.RegisterInput))
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(_a0 *auth.RegisterResult, _a1 error) *MockAuthService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(auth.RegisterInput) (*auth.RegisterResult, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
