// Code generated by mockery v2.53.5. DO NOT EDIT.

package stock_mock

import (
	models "sun-stockanalysis-api/internal/models"

	mock "github.com/stretchr/testify/mock"

	stock "sun-stockanalysis-api/internal/domains/stock"

	uuid "github.com/google/uuid"
)

// MockStockService is an autogenerated mock type for the StockService type
type MockStockService struct {
	mock.Mock
}

type MockStockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStockService) EXPECT() *MockStockService_Expecter {
	return &MockStockService_Expecter{mock: &_m.Mock}
}

// CreateStock provides a mock function with given fields: input
func (_m *MockStockService) CreateStock(input stock.CreateStockInput) error {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for CreateStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(stock.CreateStockInput) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStockService_CreateStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStock'
type MockStockService_CreateStock_Call struct {
	*mock.Call
}

// CreateStock is a helper method to define mock.On call
//   - input stock.CreateStockInput
func (_e *MockStockService_Expecter) CreateStock(input interface{}) *MockStockService_CreateStock_Call {
	return &MockStockService_CreateStock_Call{Call: _e.mock.On("CreateStock", input)}
}

func (_c *MockStockService_CreateStock_Call) Run(run func(input stock.CreateStockInput)) *MockStockService_CreateStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(stock.CreateStockInput))
	})
	return _c
}

func (_c *MockStockService_CreateStock_Call) Return(_a0 error) *MockStockService_CreateStock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStockService_CreateStock_Call) RunAndReturn(run func(stock.CreateStockInput) error) *MockStockService_CreateStock_Call {
	_c.Call.Return(run)
	return _c
}

// GetStock provides a mock function with given fields: id
func (_m *MockStockService) GetStock(id uuid.UUID) (*models.Stock, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetStock")
	}

	var r0 *models.Stock
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Stock, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Stock); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Stock)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStockService_GetStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStock'
type MockStockService_GetStock_Call struct {
	*mock.Call
}

// GetStock is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockStockService_Expecter) GetStock(id interface{}) *MockStockService_GetStock_Call {
	return &MockStockService_GetStock_Call{Call: _e.mock.On("GetStock", id)}
}

func (_c *MockStockService_GetStock_Call) Run(run func(id uuid.UUID)) *MockStockService_GetStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockStockService_GetStock_Call) Return(_a0 *models.Stock, _a1 error) *MockStockService_GetStock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStockService_GetStock_Call) RunAndReturn(run func(uuid.UUID) (*models.Stock, error)) *MockStockService_GetStock_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStockService creates a new instance of MockStockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStockService {
	mock := &MockStockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
